services:
  stable:
    container_name: dartpad-stable
    platform: linux/amd64
    build:
      context: .
      dockerfile: pkgs/dart_services/Dockerfile
      args:
        FLUTTER_CHANNEL: stable
        GCLOUD_AUTH: ${GCLOUD_AUTH}
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"

  beta:
    container_name: dartpad-beta
    platform: linux/amd64
    build:
      context: .
      dockerfile: pkgs/dart_services/Dockerfile
      args:
        FLUTTER_CHANNEL: beta
        GCLOUD_AUTH: ${GCLOUD_AUTH}
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8080"

  main:
    container_name: dartpad-main
    platform: linux/amd64
    build:
      context: .
      dockerfile: pkgs/dart_services/Dockerfile
      args:
        FLUTTER_CHANNEL: main
        GCLOUD_AUTH: ${GCLOUD_AUTH}
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8082:8080"